# dip task2 params

# hsv upper and lower
h_lower: 0
s_lower: 115
v_lower: 100

pile_h_upper: 10 # 10 for pile
nurse_h_upper: 255 # 255 for nurse 
s_upper: 255
v_upper: 255

# adaptive matchtemplate
nurse_threshold: 0.3
nurse_scaleStep: 0.1
nurse_minScale: 0.2
nurse_maxScale: 1.0

pile_threshold: 0.72
pile_scaleStep: 0.1
pile_minScale: 0.2
pile_maxScale: 1.8 # default 1.8

# 桶相对于机器人距离阈值
pile_thre: 0.5 # default 0.5

vel: 0.5 # default 0.5
vel_coef: 0.1 # default 0.1
angular_coef: -0.1 # default -0.1
pile_pre:  2.0 # default 2

nurse_pre: 0.5 # nurse的pre
nurse_coef: 1.0 # nurse的距离_coef
