# dip task2 params

# hsv upper and lower
h_lower: 0
s_lower: 115
v_lower: 100

pile_h_upper: 10 # 10 for pile
nurse_h_upper: 255 # 255 for nurse 
s_upper: 255
v_upper: 255

# adaptive matchtemplate
nurse_threshold: 0.4
nurse_scaleStep: 0.1
nurse_minScale: 0.2
nurse_maxScale: 1.0

pile_threshold: 0.8 
pile_scaleStep: 0.2
pile_minScale: 0.2
pile_maxScale: 1.8
